### ISSUE TITLE
1.7.8.10

### ISSUE THREAD

**Issue by KamykJr** [indaco/instantseo#1]
Hello. Is it work with Presta 1.7.8.10 ?

**Comment by indaco** [comment]
> Hello. Is it work with Presta 1.7.8.10 ?
> 
> 

Didn't test against that version. 

You could give it a try and report any issue. 

Thanks

**Comment by KamykJr** [comment]
I have tried. When I am trying to install it, I receive a message that this version isn't correct with the Presta revision.

**Comment by indaco** [comment]
- clone or fork the project
- Edit the "instantseo.php" file to include your target version. 
- create a zip archive
- install your local zip file. 

If it works, submit a PR

**Comment by KamykJr** [comment]
Thank you very much :D Works perfect fine.
